//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HackerNews.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int PostId { get; set; }
        public int RelatedUserId { get; set; }
        public int Vote { get; set; }
        public string URL { get; set; }
        public string Title { get; set; }
    
        public virtual User User { get; set; }
    }
}
